### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [snapsnapturtle/waiter#1]
on this code:
https://github.com/snapsnapturtle/waiter/blob/master/api/orders/orders.get.js
you might want to consider using method `task` instead of `tx`, since you are not changing the data there, you are only reading the data ;)

Also, use of `oneOrNone` implies that you are ready to handle the situation when it resolves with `null`, which your code below doesn't verify.

See the difference between methods [one](http://vitaly-t.github.io/pg-promise/Database.html#.one) and [oneOrNone](http://vitaly-t.github.io/pg-promise/Database.html#.oneOrNone).

**Comment by snapsnapturtle** [comment]
thanks so much for the hint, ill get right on it :+1:
